-- =====================================================
-- BUSINESS QUESTION 1
-- What are the overall sales performance metrics?
-- =====================================================

SELECT
    COUNT(*) AS [Total Transactions],
    SUM(SaleAmount) AS [Total Revenue],
    AVG(SaleAmount) AS [Average Sale],
    MIN(SaleAmount) AS [Smallest Sale],
    MAX(SaleAmount) AS [Largest Sale],
    SUM(UnitsSold) AS [Total Units Sold]
FROM dbo.Sales;


-- =====================================================
-- BUSINESS QUESTION 2
-- How is each sales representative performing?
-- =====================================================

SELECT
    SalesRep,
    COUNT(*) AS [Total Deals],
    SUM(SaleAmount) AS [Total Revenue],
    AVG(SaleAmount) AS [Average Deal Amount]
FROM dbo.Sales
GROUP BY SalesRep
ORDER BY [Total Revenue] DESC;


-- =====================================================
-- BUSINESS QUESTION 3
-- How much revenue is generated by region and category?
-- =====================================================

SELECT
    Region,
    ProductCategory,
    COUNT(*) AS [Transaction Count],
    SUM(SaleAmount) AS [Category Revenue]
FROM dbo.Sales
GROUP BY
    Region,
    ProductCategory
ORDER BY
    Region ASC,
    [Category Revenue] DESC;


-- =====================================================
-- BUSINESS QUESTION 4
-- How are sales representatives performing in the East?
-- =====================================================

SELECT
    SalesRep,
    SUM(SaleAmount) AS [East Revenue],
    AVG(SaleAmount) AS [Average East Deal]
FROM dbo.Sales
WHERE Region = 'East'
GROUP BY SalesRep
ORDER BY [East Revenue] DESC;


-- =====================================================
-- BUSINESS QUESTION 5
-- Which product categories are top performers?
-- =====================================================

SELECT
    ProductCategory,
    COUNT(*) AS [Transaction Count],
    SUM(SaleAmount) AS [Total Revenue]
FROM dbo.Sales
GROUP BY ProductCategory
HAVING
    SUM(SaleAmount) > 10000.00
    AND COUNT(*) > 4
ORDER BY [Total Revenue] DESC;


-- =====================================================
-- BUSINESS QUESTION 6
-- How can individual sales be categorized by value?
-- =====================================================

SELECT
    SaleID,
    SalesRep,
    ProductCategory,
    SaleAmount,
    CASE
        WHEN SaleAmount >= 3500.00 THEN 'High Value'
        WHEN SaleAmount BETWEEN 1500.00 AND 3499.99 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS [SaleTier]
FROM dbo.Sales
ORDER BY SaleAmount DESC;


-- =====================================================
-- BUSINESS QUESTION 7
-- What is each sales rep's revenue, credit-card revenue,
-- and number of high-value deals?
-- =====================================================

SELECT
    SalesRep,
    SUM(SaleAmount) AS [Total Revenue],
    SUM(CASE WHEN PaymentMethod = 'Credit Card' THEN SaleAmount ELSE 0 END) AS [Credit Card Revenue],
    COUNT(CASE WHEN SaleAmount >= 3000.00 THEN 1 END) AS [High Value Deals Count]
FROM dbo.Sales
GROUP BY SalesRep
ORDER BY [Total Revenue] DESC;
